export const ADD_NEW_CLIENT_REQUEST="ADD_NEW_CLIENT_REQUEST"
export const ADD_NEW_CLIENT_SUCCESS="ADD_NEW_CLIENT_SUCCESS"
export const ADD_NEW_CLIENT_FAIL="ADD_NEW_CLIENT_FAIL"


// export const GET_CLIENTS_REQUEST="GET_CLIENTS_REQUEST"
// export const GET_CLIENTS_SUCCESS="GET_CLIENTS_SUCCESS"
// export const GET_CLIENTS_FAIL="GET_CLIENTS_FAIL"

export const GET_CLIENT_REQUEST="GET_CLIENT_REQUEST"
export const GET_CLIENT_SUCCESS="GET_CLIENT_SUCCESS"
export const GET_CLIENT_FAIL="GET_CLIENT_FAIL"


export const UPDATE_CLIENT_REQUEST="UPDATE_CLIENT_REQUEST"
export const UPDATE_CLIENT_SUCCESS="UPDATE_CLIENT_SUCCESS"
export const UPDATE_CLIENT_FAIL="UPDATE_CLIENT_FAIL"


export const DELETE_CLIENT_REQUEST="DELETE_CLIENT_REQUEST"
export const DELETE_CLIENT_SUCCESS="DELETE_CLIENT_SUCCESS"
export const DELETE_CLIENT_FAIL="DELETE_CLIENT_FAIL"


export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"
export const LOUGOUT="LOUGOUT" 