export const ADD_NEW_LAWYER_REQUEST="ADD_NEW_LAWYER_REQUEST"
export const ADD_NEW_LAWYER_SUCCESS="ADD_NEW_LAWYER_SUCCESS"
export const ADD_NEW_LAWYER_FAIL="ADD_NEW_LAWYER_FAIL"


export const GET_LAWYERS_REQUEST="GET_LAWYERS_REQUEST"
export const GET_LAWYERS_SUCCESS="GET_LAWYERS_SUCCESS"
export const GET_LAWYERS_FAIL="GET_LAWYERS_FAIL"

export const GET_LAWYER_REQUEST="GET_LAWYER_REQUEST"
export const GET_LAWYER_SUCCESS="GET_LAWYER_SUCCESS"
export const GET_LAWYER_FAIL="GET_LAWYER_FAIL"


export const UPDATE_LAWYER_REQUEST="UPDATE_LAWYER_REQUEST"
export const UPDATE_LAWYER_SUCCESS="UPDATE_LAWYER_SUCCESS"
export const UPDATE_LAWYER_FAIL="UPDATE_LAWYER_FAIL"


export const DELETE_LAWYER_REQUEST="DELETE_LAWYER_REQUEST"
export const DELETE_LAWYER_SUCCESS="DELETE_LAWYER_SUCCESS"
export const DELETE_LAWYER_FAIL="DELETE_LAWYER_FAIL"


export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"
export const LOUGOUT="LOUGOUT" 