export const ADD_NEW_SECRETARY_REQUEST="ADD_NEW_SECRETARY_REQUEST"
export const ADD_NEW_SECRETARY_SUCCESS="ADD_NEW_SECRETARY_SUCCESS"
export const ADD_NEW_SECRETARY_FAIL="ADD_NEW_SECRETARY_FAIL"


// export const GET_SECRETARIES_REQUEST="GET_SECRETARIES_REQUEST"
// export const GET_SECRETARIES_SUCCESS="GET_SECRETARIES_SUCCESS"
// export const GET_SECRETARIES_FAIL="GET_SECRETARIES_FAIL"

export const GET_SECRETARY_REQUEST="GET_SECRETARY_REQUEST"
export const GET_SECRETARY_SUCCESS="GET_SECRETARY_SUCCESS"
export const GET_SECRETARY_FAIL="GET_SECRETARY_FAIL"


export const UPDATE_SECRETARY_REQUEST="UPDATE_SECRETARY_REQUEST"
export const UPDATE_SECRETARY_SUCCESS="UPDATE_SECRETARY_SUCCESS"
export const UPDATE_SECRETARY_FAIL="UPDATE_SECRETARY_FAIL"


export const DELETE_SECRETARY_REQUEST="DELETE_SECRETARY_REQUEST"
export const DELETE_SECRETARY_SUCCESS="DELETE_SECRETARY_SUCCESS"
export const DELETE_SECRETARY_FAIL="DELETE_SECRETARY_FAIL"


export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"
export const LOUGOUT="LOUGOUT" 